### ISSUE TITLE
[feature] 支持参考文献

### ISSUE THREAD

**Issue by gaocegege** [dyweb/SJTUThesis-Markdown#3]
支持参考文献

**Comment by bubifengyun** [comment]
请教一下，实行参考文献过程中需要特别注意啥问题吗？我的也可用链接到参考文献，就是无法在目录中显示参考文献所在页数。 谢谢啦。@gaocegege

**Comment by gaocegege** [comment]
https://github.com/dyweb/SJTUThesis-Markdown/commit/a02a2a68156070d130fcb57efcdd257b93bb9aa1

主要是要有一个 `citation_package` 的配置

**Comment by bubifengyun** [comment]
谢谢，照着改了，仍旧是不出现在目录中，其他的地方都有，就是目录没有。我再试试吧。

**Comment by bubifengyun** [comment]
找到原因了，把中间写的非常混乱的 markdown 简介给删了，把之前的代码 label 相同的给调整不同了。最后就出来参考文献了。看了标签错误也会影响参考文献的出现。
